### ISSUE TITLE
missing libstdc++.so.6 when importing pandas

### ISSUE THREAD

**Issue by vlinhart** [amancevice/docker-pandas#5]
Hello,
when trying to use the new pandas image

`amancevice/pandas:0.23.0-python3-alpine`

```
docker run  amancevice/pandas:0.23.0-python3-alpine python3 -c import pandas"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/pandas/__init__.py", line 42, in <module>
    from pandas.core.api import *
  File "/usr/lib/python3.6/site-packages/pandas/core/api.py", line 10, in <module>
    from pandas.core.groupby.groupby import Grouper
  File "/usr/lib/python3.6/site-packages/pandas/core/groupby/__init__.py", line 2, in <module>
    from pandas.core.groupby.groupby import (
  File "/usr/lib/python3.6/site-packages/pandas/core/groupby/groupby.py", line 49, in <module>
    from pandas.core.frame import DataFrame
  File "/usr/lib/python3.6/site-packages/pandas/core/frame.py", line 74, in <module>
    from pandas.core.series import Series
  File "/usr/lib/python3.6/site-packages/pandas/core/series.py", line 3978, in <module>
    Series._add_series_or_dataframe_operations()
  File "/usr/lib/python3.6/site-packages/pandas/core/generic.py", line 8891, in _add_series_or_dataframe_operations
    from pandas.core import window as rwindow
  File "/usr/lib/python3.6/site-packages/pandas/core/window.py", line 36, in <module>
    import pandas._libs.window as _window
ImportError: Error loading shared library libstdc++.so.6: No such file or directory (needed by /usr/lib/python3.6/site-packages/pandas/_libs/window.cpython-36m-x86_64-linux-gnu.so)
```

The older one `amancevice/pandas:0.22.0-python3-alpine` works ok. Now I need to add the 
`apk add --no-cache libstdc++` which I'm not sure is the correct solution.

**Comment by victornoel** [comment]
@amancevice any way to fix that? I confirm that adding libstdc++ fixes the problem.

**Comment by amancevice** [comment]
I must have missed this issue, my apologies. I accept pull requests! But in this case I'll add the `libstdc++` library and rebuild.

**Comment by amancevice** [comment]
Please try again with the latest `amancevice/pandas:0.23.4-python3-alpine` image.

**Comment by victornoel** [comment]
@amancevice works great, thanks :)
